import { createRouter as createTanStackRouter } from '@tanstack/react-router'
import { NotFoundPage } from './components/NotFoundPage'
import { routeTree } from './routeTree.gen'

/**
 * Router factory consumed by TanStack Start's generated SSR + client entries.
 *
 * The route tree is generated by the `tanstackStart()` Vite plugin from the
 * files under `src/routes`.
 */
export function getRouter() {
  const router = createTanStackRouter({
    routeTree,
    defaultPreload: 'intent',
    scrollRestoration: true,
    // Router-level fallback so every unmatched route inherits the branded,
    // theme-aware 404 (story 6-4); otherwise TanStack falls back to its generic
    // `<p>Not Found</p>`.
    defaultNotFoundComponent: NotFoundPage,
  })

  return router
}

declare module '@tanstack/react-router' {
  interface Register {
    router: ReturnType<typeof getRouter>
  }
}
