-- Story 5-19: harden the Paddle webhook and the entitlement lifecycle.
--
-- Five changes, all load-bearing for live-money behaviour:
--
--  1. `paddleWebhookEvents` — the DELIVERY idempotency store (AC-2). One row per
--     Paddle event id, inserted BEFORE any work is done; a PK conflict means the
--     delivery is a duplicate and the handler no-ops. Paddle re-signs every
--     retry with a fresh `ts`, so signature freshness never filtered retries.
--
--  2. `paddleAdjustments` — the ADJUSTMENT ledger (AC-1). A separate identity
--     from the delivery: Paddle emits BOTH `adjustment.created` and
--     `adjustment.updated` for one adjustment, as two deliveries with two
--     different event ids, so delivery-level dedup does not stop a refund being
--     counted twice. The refunded total is DERIVED by summing this table for the
--     granting transaction, never incremented in place.
--
--  3. `users.entitlementUpdatedAt` — the ordering watermark (AC-2), the
--     `occurred_at` of the newest event that changed this user's entitlement.
--     Without it, a `subscription.updated{active}` that 500s and is retried
--     AFTER `subscription.canceled` silently re-grants Premium to a cancelled
--     user (and symmetrically, a late `canceled` revokes a paying subscriber).
--
--  4. `users.lifetimeTransactionId` / `lifetimeGrantTotal` — lifetime accounting
--     (AC-1, AC-8). The grant total is recorded at grant time so a later refund
--     can be judged FULL vs PARTIAL without a second Paddle API round trip, and
--     so a zero-value or non-collecting transaction cannot grant a permanent
--     €99 entitlement.
--
--  5. `userProfiles_one_default_per_user` — at most ONE default profile per
--     user, as a DATABASE constraint (AC-4). `createDefaultProfileForUser` is
--     check-then-insert outside any transaction, and a single lifetime purchase
--     emits BOTH `transaction.paid` and `transaction.completed`; processed
--     concurrently, both saw zero rows and both inserted, and profile-scoped
--     reads then pick arbitrarily — the buyer's data appears to vanish between
--     requests. Only a constraint closes that window.
--
-- ⚠️ THE `UPDATE` BELOW IS NOT OPTIONAL AND MUST STAY AHEAD OF THE INDEX.
-- `CREATE UNIQUE INDEX` FAILS on a table that already violates it, and the race
-- this index exists to prevent has been live in production since the first
-- lifetime checkout. The UPDATE keeps the OLDEST default per user (by
-- `createdAt`, ties broken by `id` so the choice is deterministic rather than
-- whatever order the planner returns) and demotes the rest. Tombstoned rows are
-- excluded throughout: a soft-deleted default (Story 4-18) must not block
-- creating a new one.
--
-- ⚠️ THE UPDATE ALSO BUMPS `updatedAt`, AND THAT IS LOAD-BEARING — code review
-- finding. The sync pull delta is `updatedAt > since` (`server/api/sync.ts`),
-- and the client pushes `isDefault` back on any profile edit
-- (`syncBridge.ts`; `updateEntity` spreads it straight into `.set()`). Demoting
-- WITHOUT bumping `updatedAt` leaves every already-synced device holding a
-- stale `isDefault: true`; the user's next rename of that profile pushes it
-- back, violates the new unique index, and returns a non-retryable driver error
-- — which opens the sync circuit breaker and halts ALL sync for the cooldown,
-- repeatedly.
--
-- Pre-launch: no third-party users, so the demotion can only touch Lucas's own
-- rows. Generated by drizzle-kit, then hand-edited to add the dedupe.
-- Reviewed, NOT applied — migrations are a manual deploy step in this repo
-- (the 0004/0005/0011/0013/0016 precedent).

CREATE TABLE IF NOT EXISTS "paddleAdjustments" (
	"adjustmentId" varchar(255) PRIMARY KEY NOT NULL,
	"customerId" varchar(255) NOT NULL,
	"transactionId" varchar(255),
	"action" varchar(64) NOT NULL,
	"total" bigint NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "paddleWebhookEvents" (
	"eventId" varchar(255) PRIMARY KEY NOT NULL,
	"eventType" varchar(255) NOT NULL,
	"customerId" varchar(255),
	"occurredAt" bigint,
	"processedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "entitlementUpdatedAt" bigint;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "lifetimeTransactionId" varchar(255);--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "lifetimeGrantTotal" bigint;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "paddleAdjustments_customerId_idx" ON "paddleAdjustments" USING btree ("customerId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "paddleAdjustments_transactionId_idx" ON "paddleAdjustments" USING btree ("transactionId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "paddleWebhookEvents_customerId_idx" ON "paddleWebhookEvents" USING btree ("customerId");--> statement-breakpoint
UPDATE "userProfiles" AS p SET "isDefault" = false, "updatedAt" = now()
WHERE p."isDefault"
  AND NOT p."isDeleted"
  AND p."id" <> (
    SELECT q."id" FROM "userProfiles" AS q
    WHERE q."userId" = p."userId" AND q."isDefault" AND NOT q."isDeleted"
    ORDER BY q."createdAt" ASC, q."id" ASC
    LIMIT 1
  );
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "userProfiles_one_default_per_user" ON "userProfiles" USING btree ("userId") WHERE "userProfiles"."isDefault" AND NOT "userProfiles"."isDeleted";
