import { lstatSync, readdirSync } from 'node:fs'
import { join, relative, resolve, sep } from 'node:path'
import { describe, expect, it } from 'vitest'
import { DOC_PAGES } from '../../content/docs'
import { Route as RootRoute } from '../__root'

/**
 * Every page route names itself (story 40.1, FR65).
 *
 * WHY THIS IS AN ENUMERATION AND NOT A LIST OF ASSERTIONS. A per-route `head()`
 * is two lines to add and two lines to forget. Before this story EIGHT routes
 * carried one and ELEVEN did not, and nothing failed — every one of those eleven
 * silently inherited the root default, so eleven pages shared one tab title and
 * nineteen shared one meta description. A spot-check of named routes would have
 * been green throughout. This test discovers the route set instead, so a route
 * added tomorrow is covered the day it lands.
 *
 * ⚠️ THE DISCOVERY IS THE LOAD-BEARING HALF, NOT THE PER-ROUTE ASSERTION.
 * A walker whose pattern is too narrow discovers three routes, asserts three
 * routes, and passes green while sixteen have no title at all. So the route set
 * is established THREE independent ways that must agree:
 *
 *   1. `import.meta.glob` — Vite's compile-time glob (also the only way to
 *      import them: Vite cannot resolve a fully-variable `import(path)`, which
 *      is why this is a glob and not a plain readdir + dynamic import).
 *   2. `readdirSync` — a real filesystem walk, which no build-time pattern can
 *      narrow.
 *   3. `EXPECTED_ROUTE_PATHS` — written out by hand below.
 *
 * ⚠️ THEY ARE NOT FULLY INDEPENDENT, AND OVERSTATING THAT ONCE COST A REAL HOLE.
 * 1 and 2 both run their result through `isPageRouteFile`/`toRoutePath`, so a
 * bug in EITHER of those is common-mode and their agreement proves nothing about
 * it. Only the hand list is independent of that code. This is exactly how an
 * untitled `.ts` route passed 51/51 — see the note on `isPageRouteFile`. When
 * changing the classifier, mutate it and confirm the suite goes red; do not
 * infer safety from the two walkers agreeing.
 *
 * Narrowing the glob makes 1 disagree with 2. Deleting a route file without
 * updating the list makes 2 disagree with 3. Both go red.
 *
 * ⚠️ DO NOT REBUILD THIS ON `routeTree.gen.ts`. That file is gitignored
 * (`apps/web/.gitignore:2`) and generated by the TanStack plugin, which the
 * Vitest config does not load. It is absent on a fresh checkout, so a test that
 * imports it passes locally and fails in CI with a module-not-found. Nothing
 * else in the unit suite imports it — `src/test/utils.ts` builds its own route
 * tree — so there is no precedent to copy here.
 */

const ROUTES_DIR = resolve(__dirname, '..')

/** Vite resolves this glob against the filesystem at transform time. */
const routeModules = import.meta.glob('../**/*.{ts,tsx}')

/**
 * A route file is a PAGE route when it is neither the root document, nor a
 * server route, nor a test.
 *
 * ⚠️ THIS ACCEPTS `.ts` AS WELL AS `.tsx`, AND THAT IS LOAD-BEARING. The first
 * version matched `.tsx` only, on the unstated assumption that a page route
 * always contains JSX. It does not have to: a redirect-only or loader-only route
 * is legal TanStack file routing and needs no JSX. MEASURED — an untitled
 * `routes/zz-mutant.ts` passed the whole suite 51/51 GREEN, while the identical
 * route as `.tsx` went red.
 *
 * Worse, the extension check sat UPSTREAM of all three discovery opinions, so
 * the glob, the filesystem walk and the hand-written list agreed with each other
 * about a route none of them could see. THREE OPINIONS BEHIND ONE SHARED FILTER
 * ARE ONE OPINION. Server routes stay excluded by the explicit `api/` rule,
 * which is a stated rule rather than a side effect of how those files happen to
 * be written — that is what makes widening the extension safe.
 *
 * NOT handled, because this app uses none of them and a wrong guess would be
 * worse than a loud failure: route groups `(group)/`, pathless layouts
 * `_layout/`, and flat dot-notation (`docs.$docId.tsx`). Any of those derives a
 * route path matching nothing in the expected list and fails LOUDLY rather than
 * passing silently. Extend `toRoutePath` if the app adopts one.
 */
function isPageRouteFile(relPath: string): boolean {
  const p = relPath.split(sep).join('/').replace(/^\.\//, '')
  if (!/\.tsx?$/.test(p)) return false
  if (p === '__root.tsx') return false
  if (p.startsWith('api/')) return false
  if (p.includes('__tests__/')) return false
  if (/\.(test|spec)\./.test(p)) return false
  // TanStack excludes `-`-prefixed files and directories from routing, so they
  // are colocated helpers, not pages, and must not be asked for a <title>.
  if (p.split('/').some((seg) => seg.startsWith('-'))) return false
  return true
}

/** `income.tsx` -> `/income`; `index.tsx` -> `/`; `docs/index.tsx` -> `/docs`. */
function toRoutePath(relPath: string): string {
  const p = relPath
    .split(sep)
    .join('/')
    .replace(/^\.\.\//, '')
    .replace(/^\.\//, '')
  const withoutExt = p.replace(/\.tsx$/, '')
  if (withoutExt === 'index') return '/'
  return `/${withoutExt.replace(/\/index$/, '')}`
}

/** Real filesystem walk — independent of any build-time pattern. */
function walkRouteFiles(dir: string, acc: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const abs = join(dir, entry)
    if (lstatSync(abs).isDirectory()) {
      walkRouteFiles(abs, acc)
    } else {
      acc.push(relative(ROUTES_DIR, abs))
    }
  }
  return acc
}

/**
 * Every page route in the app, written out by hand.
 *
 * This list is the third opinion. Adding a route means adding it here, and that
 * is the point: the failure is a one-line edit with the test naming exactly what
 * is missing, which is cheaper than a page shipping untitled.
 */
const EXPECTED_ROUTE_PATHS = [
  '/',
  '/balance',
  '/categories',
  '/contact',
  '/docs',
  '/docs/$docId',
  '/expenses',
  '/forecasting',
  '/income',
  '/login',
  '/pricing',
  '/privacy',
  '/profiles',
  '/refund',
  '/report',
  '/retirement',
  '/savings',
  '/settings',
  '/terms',
] as const

/**
 * `head()` arguments for routes that read from their own loader.
 *
 * `/docs/$docId` builds its title from loader data, so calling its `head()` with
 * `{}` throws. The fixture is a REAL `DOC_PAGES` entry rather than an invented
 * shape, so the test cannot pass against a head that reads a field the content
 * model does not have.
 */
const HEAD_ARGS: Record<string, unknown> = {
  '/docs/$docId': {
    params: { docId: DOC_PAGES[0]?.slug },
    loaderData: { doc: DOC_PAGES[0] },
  },
}

interface MetaEntry {
  title?: string
  name?: string
  property?: string
  content?: string
}

function headMetaFor(routePath: string, mod: unknown): MetaEntry[] {
  const route = (
    mod as { Route?: { options?: { head?: (arg: unknown) => { meta?: MetaEntry[] } } } }
  ).Route
  const head = route?.options?.head
  if (!head) return []
  try {
    return head(HEAD_ARGS[routePath] ?? {})?.meta ?? []
  } catch (cause) {
    // A head() that reads loader data throws on `{}`. Say so by name: the raw
    // TypeError names a property, never the fixture that is missing.
    throw new Error(
      `head() threw for ${routePath} — if it reads loaderData, add a HEAD_ARGS fixture for it`,
      { cause }
    )
  }
}

function titleOf(meta: MetaEntry[]): string | undefined {
  return meta.find((m) => 'title' in m)?.title
}

function descriptionOf(meta: MetaEntry[]): string | undefined {
  return meta.find((m) => m.name === 'description')?.content
}

/** The root default, read from the root route rather than copied as a literal. */
const rootMeta = (RootRoute.options.head?.({} as never)?.meta ?? []) as MetaEntry[]
const ROOT_DESCRIPTION = descriptionOf(rootMeta)
const ROOT_TITLE = titleOf(rootMeta)

/**
 * Import a discovered route module by route path.
 *
 * Throws by name rather than asserting non-null: if the route set and the module
 * map ever disagree, "no route module found for /x" says what broke, where a
 * crash on `undefined()` does not.
 */
async function importRoute(routePath: string): Promise<unknown> {
  const globKey = Object.keys(routeModules).find(
    (k) => isPageRouteFile(k.replace(/^\.\.\//, '')) && toRoutePath(k) === routePath
  )
  const loader = globKey === undefined ? undefined : routeModules[globKey]
  if (!loader) {
    throw new Error(`no route module found for ${routePath}`)
  }
  return loader()
}

const globbedPagePaths = Object.keys(routeModules)
  .filter((k) => isPageRouteFile(k.replace(/^\.\.\//, '')))
  .map(toRoutePath)
  .sort()

describe('route discovery (story 40.1, AC-6)', () => {
  it('the compile-time glob and a real filesystem walk find the SAME page routes', () => {
    const walkedPagePaths = walkRouteFiles(ROUTES_DIR)
      .filter(isPageRouteFile)
      .map(toRoutePath)
      .sort()
    // Narrowing the glob pattern above breaks this and nothing else would.
    expect(globbedPagePaths).toEqual(walkedPagePaths)
  })

  it('discovers exactly the page routes this app has', () => {
    expect(globbedPagePaths).toEqual([...EXPECTED_ROUTE_PATHS].sort())
  })

  it('the root default is available to compare against', () => {
    // If this ever goes undefined the per-route "not the root default" checks
    // below would silently degrade into comparisons against `undefined`.
    expect(ROOT_TITLE).toBeTruthy()
    expect(ROOT_DESCRIPTION).toBeTruthy()
  })
})

describe('every page route names itself (story 40.1, AC-1/AC-2/AC-4)', () => {
  // Iterates the DISCOVERED set, not `EXPECTED_ROUTE_PATHS`. Both are pinned to
  // each other by the discovery test above, so today they are identical — but
  // driving the per-route assertions from the hand list would make them a pure
  // spot-check the day someone weakens that one test, which is precisely the
  // shape AC-6 forbids. Discovery drives; the hand list only cross-checks.
  for (const routePath of globbedPagePaths) {
    it(`${routePath} sets its own title and description`, async () => {
      const meta = headMetaFor(routePath, await importRoute(routePath))

      const title = titleOf(meta)
      const description = descriptionOf(meta)

      // ⚠️ Non-empty, not merely present. TanStack gates the title on
      // `if (m.title)` (headContentUtils.js), so an EMPTY-STRING title is
      // skipped and the route silently falls back to the root default with no
      // error anywhere.
      //
      // MEASURED, and not what I first assumed: it is the CONVENTION regex
      // below that actually catches `''`, not this line. Swapping `toBeTruthy`
      // for `toBeDefined` and shipping an empty title still goes red — on
      // "does not follow" — because `''` fails the suffix match. This line
      // earns its place as the better diagnostic for a MISSING title, not as
      // the guard against an empty one. Do not delete the regex on the belief
      // that this line covers emptiness; it does not cover it alone.
      expect(title, `${routePath} has no <title> of its own`).toBeTruthy()
      expect(description, `${routePath} has no meta description of its own`).toBeTruthy()

      // AC-2 + FR43 in one: the suffix carries the convention AND the brand
      // token, so a separate `toContain('Longhand Budget')` could never fail
      // after this and is not written. Same for a `not.toBe(ROOT_TITLE)` — the
      // root title ends "…privacy and control", so it cannot match this suffix.
      // Dead assertions that read as guards are worse than no assertion.
      expect(title, `${routePath} does not follow "<Page> · Longhand Budget"`).toMatch(
        / · Longhand Budget$/
      )

      // AC-4: the description must be the PAGE'S, not the shared root default.
      // This one is NOT dead — nothing above constrains the description's value.
      expect(description, `${routePath} still serves the root default description`).not.toBe(
        ROOT_DESCRIPTION
      )

      // ⚠️ Exactly one of each, because this file reads with `find()` (FIRST
      // match) while the renderer walks a route's meta array BACKWARDS and keeps
      // the LAST (`headContentUtils.js`: `for (j = metas.length - 1; j >= 0; j--)`
      // with a first-wins `metaByAttribute` map). With duplicates in one route's
      // array the two disagree, and every assertion above would be checking a
      // value the browser never serves.
      expect(
        meta.filter((m) => 'title' in m),
        `${routePath} declares more than one title`
      ).toHaveLength(1)
      expect(
        meta.filter((m) => m.name === 'description'),
        `${routePath} declares more than one description`
      ).toHaveLength(1)
    })
  }

  /**
   * Collected inside ONE test rather than accumulated across `it` blocks.
   * Shared mutable state between tests is only correct while the runner happens
   * to execute them in file order: under `sequence.shuffle`, `.concurrent`, a
   * `-t` filter or a retry, a per-route version of this check silently degrades
   * to vacuous — or false-fails when a retried route meets its own title from
   * the first attempt.
   */
  it('no two routes share a title', async () => {
    const byTitle = new Map<string, string[]>()
    for (const routePath of globbedPagePaths) {
      const title = titleOf(headMetaFor(routePath, await importRoute(routePath)))
      if (title === undefined) continue // reported per-route above
      byTitle.set(title, [...(byTitle.get(title) ?? []), routePath])
    }
    // Two tabs a user cannot tell apart is the defect this story exists to fix,
    // so a duplicate title is a failure and not a style note.
    const clashes = [...byTitle.entries()].filter(([, paths]) => paths.length > 1)
    expect(clashes, `routes sharing a title: ${JSON.stringify(clashes)}`).toEqual([])
  })
})

/**
 * AC-2: the eight titles that already shipped must come through this story
 * byte-identical. They are pinned as exact strings — a "still ends with the
 * brand" check would pass while the page half was reworded.
 */
describe('pre-existing titles are unchanged (story 40.1, AC-2)', () => {
  const PINNED: Record<string, string> = {
    '/categories': 'Categories · Longhand Budget',
    '/settings': 'Settings · Longhand Budget',
    '/report': 'Financial summary · Longhand Budget',
    '/contact': 'Contact · Longhand Budget',
    '/pricing': 'Pricing · Longhand Budget',
    '/terms': 'Terms of Service · Longhand Budget',
    '/privacy': 'Privacy Policy · Longhand Budget',
    '/refund': 'Refund & Cancellation Policy · Longhand Budget',
  }

  for (const [routePath, expected] of Object.entries(PINNED)) {
    it(`${routePath} still reads exactly "${expected}"`, async () => {
      expect(titleOf(headMetaFor(routePath, await importRoute(routePath)))).toBe(expected)
    })
  }
})

/**
 * `/docs/$docId` is the only route whose head has two branches, so both are
 * exercised. The unresolved branch is not hypothetical: `head()` runs while the
 * loader is pending and for the `notFound()` an unknown slug throws, which is
 * why `loaderData` is optional and why reading it unguarded does not compile.
 */
describe('/docs/$docId head branches (story 40.1)', () => {
  it('has documents to assert against', () => {
    // Without this, every per-doc assertion below would vacuously pass on an
    // empty list — the loop would simply not run.
    expect(DOC_PAGES.length).toBeGreaterThan(0)
  })

  /**
   * EVERY doc, not just the first. The route enumerates its content the same way
   * this file enumerates routes; pinning one fixture would leave a doc added
   * later with an empty description shipping `content=""` and nothing red. Note
   * that `toBe(doc.description)` would also pass with BOTH sides `undefined`,
   * which is why each field is separately asserted non-empty.
   */
  for (const doc of DOC_PAGES) {
    it(`/docs/${doc.slug} is named for its own document`, async () => {
      const mod = await importRoute('/docs/$docId')
      const head = (mod as { Route: { options: { head: (a: unknown) => { meta?: MetaEntry[] } } } })
        .Route.options.head
      const meta = head({ params: { docId: doc.slug }, loaderData: { doc } })?.meta ?? []

      expect(doc.title, `DOC_PAGES entry ${doc.slug} has no title`).toBeTruthy()
      expect(doc.description, `DOC_PAGES entry ${doc.slug} has no description`).toBeTruthy()
      expect(titleOf(meta)).toBe(`${doc.title} · Longhand Budget`)
      expect(descriptionOf(meta)).toBe(doc.description)
    })
  }

  it('falls back to naming the section when no document is resolved', async () => {
    const mod = await importRoute('/docs/$docId')
    const head = (mod as { Route: { options: { head: (a: unknown) => { meta?: MetaEntry[] } } } })
      .Route.options.head
    // Called with NO loaderData — the pending and not-found states.
    const meta = head({})?.meta ?? []
    // The exact pin below already proves no document title leaked in, so no
    // `not.toContain(someDocTitle)` is written: that would false-fail the day a
    // doc is titled "Documentation".
    expect(titleOf(meta)).toBe('Documentation · Longhand Budget')
    expect(descriptionOf(meta)).toBeTruthy()
  })
})
